/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package J2025_17_06.DesafioPokemon;

import javax.swing.DefaultListModel;

/**
 *
 * @author BRUNOCESARSILVADESOU
 */
public class ComputerBag extends javax.swing.JFrame {

    DefaultListModel<String> bagListModel = new DefaultListModel<>();
    DefaultListModel<String> computerListModel = new DefaultListModel<>();

    Pokemon[] pokemons = new Pokemon[]{
        new Pokemon("Pikachu", "Eletrico", 321),
        new Pokemon("Charmander", "Fogo", 289),
        new Pokemon("Squirtle", "Agua", 301),
        new Pokemon("Bulbasaur", "Planta", 310),
        new Pokemon("Jigglypuff", "Normal", 275),
        new Pokemon("Gengar", "Fantasma", 350),
        new Pokemon("Onix", "Pedra", 360),
        new Pokemon("Eevee", "Normal", 298),
        new Pokemon("Machop", "Lutador", 305),
        new Pokemon("Abra", "Psiquico", 270)
    };

    /**
     * Creates new form ComputerBag
     */
    public ComputerBag() {
        initComponents();

        for (Pokemon pokemon : pokemons) {
            computerListModel.addElement(pokemon.nome + " | " + pokemon.tipo + " | " + pokemon.nivel);
        }

        computerList.setModel(computerListModel);
        bagList.setModel(bagListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        computerList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        bagList = new javax.swing.JList<>();
        computerLabel = new javax.swing.JLabel();
        bagLabel = new javax.swing.JLabel();
        toComputerButton = new javax.swing.JButton();
        toBagButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 176, 24));

        computerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(computerList);

        bagList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(bagList);

        computerLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        computerLabel.setForeground(new java.awt.Color(0, 0, 0));
        computerLabel.setText("PC");

        bagLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bagLabel.setForeground(new java.awt.Color(0, 0, 0));
        bagLabel.setText("BAG");

        toComputerButton.setText("<<<<<<<<<");
        toComputerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toComputerButtonActionPerformed(evt);
            }
        });

        toBagButton1.setText(">>>>>>>>>");
        toBagButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBagButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(computerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bagLabel)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(toBagButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(toComputerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computerLabel)
                    .addComponent(bagLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toComputerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toBagButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toComputerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toComputerButtonActionPerformed

        String pokemonSelecionado = this.bagList.getSelectedValue();
        if (pokemonSelecionado != null) {
            this.computerListModel.addElement(pokemonSelecionado);

            int index = bagList.getSelectedIndex();
            bagListModel.remove(index);
        }

    }//GEN-LAST:event_toComputerButtonActionPerformed

    private void toBagButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBagButton1ActionPerformed
        // TODO add your handling code here:
        String pokemonSelecionado = this.computerList.getSelectedValue();
        
        if (pokemonSelecionado != null && this.bagListModel.getSize() < 6) {
            this.bagListModel.addElement(pokemonSelecionado);

            int index = computerList.getSelectedIndex();
            computerListModel.remove(index);
        }
    }//GEN-LAST:event_toBagButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerBag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bagLabel;
    private javax.swing.JList<String> bagList;
    private javax.swing.JLabel computerLabel;
    private javax.swing.JList<String> computerList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton toBagButton1;
    private javax.swing.JButton toComputerButton;
    // End of variables declaration//GEN-END:variables
}
