/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package J2025_04_06.InterfaceGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author BRUNOCESARSILVADESOU
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        numero2label = new javax.swing.JLabel();
        numero2input = new javax.swing.JTextField();
        btnAdicao = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        btnMultiplicacao = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        numero1input = new javax.swing.JTextField();
        numero1label = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContainer.setBackground(new java.awt.Color(233, 233, 233));

        resultado.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        resultado.setForeground(new java.awt.Color(51, 51, 51));
        resultado.setText("Resultado: ");

        title1.setFont(new java.awt.Font("Malgun Gothic", 2, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 51, 51));
        title1.setText("Interface");

        numero2label.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        numero2label.setForeground(new java.awt.Color(51, 51, 51));
        numero2label.setText("Numero 2");

        numero2input.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        numero2input.setText("Insira número 2");
        numero2input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2inputActionPerformed(evt);
            }
        });

        btnAdicao.setBackground(new java.awt.Color(255, 102, 51));
        btnAdicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicao.setForeground(new java.awt.Color(51, 51, 51));
        btnAdicao.setText("ADIÇÃO");
        btnAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicaoActionPerformed(evt);
            }
        });

        title2.setFont(new java.awt.Font("Malgun Gothic", 3, 36)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 153, 51));
        title2.setText("Calculator");

        btnMultiplicacao.setBackground(new java.awt.Color(255, 102, 51));
        btnMultiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMultiplicacao.setForeground(new java.awt.Color(51, 51, 51));
        btnMultiplicacao.setText("MULTIPLICAÇÃO");
        btnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacaoActionPerformed(evt);
            }
        });

        btnDivisao.setBackground(new java.awt.Color(255, 102, 51));
        btnDivisao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDivisao.setForeground(new java.awt.Color(51, 51, 51));
        btnDivisao.setText("DIVISÃO");
        btnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisaoActionPerformed(evt);
            }
        });

        btnSubtracao.setBackground(new java.awt.Color(255, 102, 51));
        btnSubtracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubtracao.setForeground(new java.awt.Color(51, 51, 51));
        btnSubtracao.setText("SUBTRAÇÃO");
        btnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtracaoActionPerformed(evt);
            }
        });

        numero1input.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        numero1input.setText("Insira número 2");
        numero1input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1inputActionPerformed(evt);
            }
        });

        numero1label.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        numero1label.setForeground(new java.awt.Color(51, 51, 51));
        numero1label.setText("Numero 1");

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultado)
                    .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                            .addGap(307, 307, 307)
                            .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainContainerLayout.createSequentialGroup()
                            .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainContainerLayout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(numero2input, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numero1input, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(mainContainerLayout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numero1label)
                                        .addComponent(numero2label))))
                            .addGap(145, 145, 145)
                            .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title1)
                    .addComponent(title2))
                .addGap(15, 15, 15)
                .addComponent(numero1label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero1input, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addComponent(numero2label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero2input, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(resultado)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero2inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero2inputActionPerformed

    private void btnAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicaoActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(numero1input.getText());
        Double num2 = Double.valueOf(numero2input.getText());
        resultado.setText("Resultado: "+ (num1 + num2));
    }//GEN-LAST:event_btnAdicaoActionPerformed

    private void btnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacaoActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(numero1input.getText());
        Double num2 = Double.valueOf(numero2input.getText());
        resultado.setText("Resultado: "+ (num1 * num2));
    }//GEN-LAST:event_btnMultiplicacaoActionPerformed

    private void btnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisaoActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(numero1input.getText());
        Double num2 = Double.valueOf(numero2input.getText());
        resultado.setText("Resultado: "+ (num1 / num2));
    }//GEN-LAST:event_btnDivisaoActionPerformed

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtracaoActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(numero1input.getText());
        Double num2 = Double.valueOf(numero2input.getText());
        resultado.setText("Resultado: "+ (num1 - num2));
    }//GEN-LAST:event_btnSubtracaoActionPerformed

    private void numero1inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero1inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicao;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JTextField numero1input;
    private javax.swing.JLabel numero1label;
    private javax.swing.JTextField numero2input;
    private javax.swing.JLabel numero2label;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
